### PR TITLE
master-qa-jsf

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-60487

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Hi @melodywu 
Thank you very much for fixing the SF issues, I combined them into one commit: https://github.com/Hanlf/liferay-portal/pull/169/commits/2279101cd36f9e2279dea471e2b93fb4ad75db52
Good job for the JSF test!

**Pull request closed without merging**
