### PR TITLE
master-qa-50005

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-50005
Can cherry pick to 7.2.x
cc @GinsonRen

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
No test changes needed :)

**Comment by Hanlf** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74909
https://github.com/brianchandotcom/liferay-portal-ee/pull/25157

**Pull request closed without merging**
