### PR TITLE
master-lrqa-56537

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-56537

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Make another fix here: https://github.com/brianchandotcom/liferay-portal/pull/86158/commits/b62e101aaa931adab9c1a2e9b5b4c0bbfd41a0f4, see details under the ticket comment

**Comment by Hanlf** [comment]
Send here: https://github.com/brianchandotcom/liferay-portal/pull/86158

**Pull request closed without merging**
