### PR TITLE
LPS-98639 Add tests.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @Hanlf,

I need you to execute the same test of the issue: https://issues.liferay.com/browse/LPS-96944 with this pull request.

Thanks!!!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:bundle

**Comment by achaparro** [comment]
Just started reviewing :)

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
