### PR TITLE
master-qa-45679

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-45679

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by HarryC0204** [comment]
@GinsonRen

**Comment by Hanlf** [comment]
No test changes needed :)

**Comment by Hanlf** [comment]
Pushed to AChiang.
[austinchiang#339](https://github.com/austinchiang/liferay-portal/pull/339).

**Pull request closed without merging**
