### PR TITLE
master-qa-44976

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-44976

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:relevant

**Comment by suilin** [comment]
@GinsonRen

**Comment by Hanlf** [comment]
No test changes needed :)

**Comment by Hanlf** [comment]
Pushed to AChiang.
[austinchiang#339](https://github.com/austinchiang/liferay-portal/pull/339).

**Pull request closed without merging**
