### PR TITLE
LRQA-49996, LRQA-50001, LRQA-50002 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-49996
https://issues.liferay.com/browse/LRQA-50001
https://issues.liferay.com/browse/LRQA-50002
Can cherry pick to 7.2.x
cc @GinsonRen

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Rebase error, please resend it @Songyuewen

**Comment by Hanlf** [comment]
No test changes needed :)

**Comment by Hanlf** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/74967
https://github.com/brianchandotcom/liferay-portal-ee/pull/25167

**Pull request closed without merging**
