### PR TITLE
master-lrqa-51653

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-51653
https://issues.liferay.com/browse/LRQA-51651

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
@jeremy-Ch,
No need one update one commit, it would be better if combine these commits into one commit or one ticket one commit.

**Comment by Hanlf** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/77706

**Pull request closed without merging**
